name: sensors-unity
version: "24.05"
confinement: strict
grade: stable
summary: A simple sensors GUI for the Unity Desktop
description:  Allows monitoring the output of the `sensors` command graphically.
base: core20

apps:
  sensors-unity:
    command: bin/sensors-gui.py
    plugs: [unity7, hardware-observe]
    extensions: [gnome-3-38]
    environment:
      PYTHONPATH: $SNAP/gnome-platform/usr/lib/python3/dist-packages:$SNAP/usr/lib/python3/dist-packages

slots:
  # for GtkApplication registration
  sensors-gui:
    interface: dbus
    bus: session
    name: net.rojtberg.sensors-gui

parts:
    lm-sensors:
        plugin: make
        source: https://github.com/lm-sensors/lm-sensors.git
        build-packages:
          - bison
          - flex
          - make
          - gcc
    sensors-unity:
        plugin: python
        source: .
        python-packages: ["--target", $SNAPCRAFT_PART_INSTALL, "."]
        build-packages:
            - python3-distutils-extra
        stage-packages:
            - gir1.2-unity-5.0
        build-environment:
            - SNAPCRAFT_PYTHON_VENV_ARGS: --system-site-packages
        stage:
            - -bin/python3 # workaround for gnome-3-38-2004
    cleanup:
      after:  [sensors-unity]
      plugin: nil
      build-snaps:
        - core20
        - gnome-3-38-2004
      override-prime: |
        set -eux
        for snap in "core20" "gnome-3-38-2004"; do  # List all content-snaps and base snaps you're using here
            cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
        done
