name: sensors-unity
version: "22.11"
confinement: strict
grade: stable
summary: A simple sensors GUI for the Unity Desktop
description:  Allows monitoring the output of the `sensors` command graphically.
base: core18

apps:
  sensors-unity:
    command: sensors-gui.py
    plugs: [unity7, hardware-observe]
    extensions: [gnome-3-28]
    environment:
      PYTHONPATH: $SNAP/gnome-platform/usr/lib/python3/dist-packages

slots:
  # for GtkApplication registration
  sensors-gui:
    interface: dbus
    bus: session
    name: net.rojtberg.sensors-gui

parts:
    lm-sensors:
        plugin: make
        source: https://github.com/lm-sensors/lm-sensors.git
        build-packages:
          - bison
          - flex
          - make
          - gcc
    sensors-unity:
        plugin: python
        source: .
        stage-packages:
            - python3-distutils-extra
            - gir1.2-unity-5.0
        stage:
            # clutter pulled by distutils extra
            - -usr/share/perl
            - -usr/lib/*/perl
    cleanup:
      after:  [sensors-unity]
      plugin: nil
      build-snaps:
        - core18
        - gnome-3-28-1804
      override-prime: |
        set -eux
        for snap in "core18" "gnome-3-28-1804"; do  # List all content-snaps and base snaps you're using here
            cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
        done
